try {
    const conn = await sequelize.authenticate()
    console.log('Connection has been established successfully.', conn);
}catch (e){
    console.error('Unable to connect to the database:', e);
}
sequelize.authenticate().then(() => {
    console.log('Connection has been established successfully.');
}).catch(error => {
    console.error('Unable to connect to the database:', error);
})